apiVersion: apps/v1
kind: Deployment
metadata:
  name: dremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dremio
  template:
    metadata:
      labels:
        app: dremio
    spec:
      containers:
      - name: dremio
        image: dremio/dremio-oss:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        ports:
        - containerPort: 9047
        - containerPort: 31010
        - containerPort: 32010